[package]
name = "layer_config"
version = "0.1.0"
edition = "2021"

[dependencies]
layer_config_derive = { path = "../layer_config_derive" }

[dev-dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
